title: Ruby on Roads
description: A developer on the road.

paginate_path: "blog/page:num/"
permalink: blog/:title/
markdown: kramdown
highlighter: rouge
paginate: 10

social:
   github: mikrobi
   twitter: classisch
   email: jakob.class@gmail.com

gems:
  - jekyll-feed
  - jemoji
  - jekyll-paginate
  - support-for

navigation:
 - title: Home
   url: /index.html

google_analytics: "UA-105302462-1"
